In [87]:
import pandas as pd
import numpy as np
import copy, time
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import LabelEncoder

In [88]:
data_path = 'C:/Users/User/Desktop/2nd-ML100Days/'
train_df = pd.read_csv(data_path + 'train.csv',header = None)
train_label = pd.read_csv(data_path + 'trainLabels.csv',header = None)
test_df = pd.read_csv(data_path +'test.csv',header = None)

# train_y
train_label.columns = ['Solution']
print(f' training data shape : {train_df.shape} ')
print(f' training label shape : {train_label.shape} ')
print(f' testing data shape : {test_df.shape} ')

 training data shape : (1000, 40)
 training label shape : (1000, 1)
 testing data shape : (9000, 40)

In [89]:
total_df = pd.concat([train_df, test_df], axis = 0)
total_df.head()

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,0.299403,-1.226624,1.498425,-1.176150,5.289853,0.208297,2.404498,1.594506,-0.051608,0.663234,...,-0.850465,-0.622990,-1.833057,0.293024,3.552681,0.717611,3.305972,-2.715559,-2.682409,0.101050
1,-1.174176,0.332157,0.949919,-1.285328,2.199061,-0.151268,-0.427039,2.619246,-0.765884,-0.093780,...,-0.819750,0.012037,2.038836,0.468579,-0.517657,0.422326,0.803699,1.213219,1.382932,-1.817761
2,1.192222,-0.414371,0.067054,-2.233568,3.658881,0.089007,0.203439,-4.219054,-1.184919,-1.240310,...,-0.604501,0.750054,-3.360521,0.856988,-2.751451,-1.582735,1.672246,0.656438,-0.932473,2.987436
3,1.573270,-0.580318,-0.866332,-0.603812,3.125716,0.870321,-0.161992,4.499666,1.038741,-1.092716,...,1.022959,1.275598,-3.480110,-1.065252,2.153133,1.563539,2.767117,0.215748,0.619645,1.883397
4,-0.613071,-0.644204,1.112558,-0.032397,3.490142,-0.011935,1.443521,-4.290282,-1.761308,0.807652,...,0.513906,-1.803473,0.518579,-0.205029,-4.744566,-1.520015,1.830651,0.870772,-1.894609,0.408332

In [90]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [91]:
train_x = total_df[:len(train_df)]
test_x = total_df[len(train_df):]
clf = GradientBoostingClassifier()

In [92]:
x_train, x_test, y_train, y_test = train_test_split(train_x,train_label, test_size = 0.2, random_state = 2019)
clf.fit(x_train, y_train)
pred = clf.predict(x_test)
print(f' Accuracy with non-tuned classifier : {metrics.accuracy_score(pred,y_test)}')

c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

 Accuracy with non-tuned classifier : 0.865

In [93]:
# 用測試資料集X預測Y,我們不知道正確的Y是多少
prediction = clf.predict(test_x)

In [94]:
output = pd.DataFrame({'Id' : np.arange(1,len(test_x)+1,1), 'Solution' : prediction})
output.head(10)

   Id  Solution
0   1         1
1   2         0
2   3         0
3   4         0
4   5         1
5   6         0
6   7         0
7   8         1
8   9         0
9  10         0

In [95]:
output.to_csv('Submission.csv', index = False)